### ISSUE TITLE
Missing folder 'utils'

### ISSUE THREAD

**Issue by absdnd** [daerduoCarey/structurenet#11]
Hello,

Thank you for releasing the code for this interesting work.

In the folder, `partnet_edges/detect_all_edges.py`, the `utils` folder seems to be missing. Could you update the code to include that folder?

**Comment by daerduoCarey** [comment]
I think that is not used at all? Try to just delete it?

**Comment by aditya-vora** [comment]
Hi, 

I am trying to just run the `partnet_edges/detect_all_edges.py` , it seems the file is importing some other `geometry_utils.py` file which I am not able to find in the repo. Could you update the code to include these files, or am I missing something?

**Comment by aditya-vora** [comment]
Okay I think I figured it out. Its seems the filename and the functions are renamed a bit. I can see functions performing similar tasks in `code/utils.py`. The functions are `load_obj` and `sample_pc`.

**Comment by daerduoCarey** [comment]
the full geometry_utils.py can be found here: https://github.com/daerduoCarey/partnet_dataset/blob/master/scripts/geometry_utils.py
