### ISSUE TITLE
RuntimeError: Error building extension 'cd'

### ISSUE THREAD

**Issue by Icxa** [daerduoCarey/structurenet#13]
Hi, 
I have been trying to build extension for chamfer_distance but it fails. The reason for failure seems to be 
```
nvcc fatal   : Unknown option '-generate-dependencies-with-compile'
ninja: build stopped: subcommand failed.
```
Can you please help to resolve this issue?
Thank you very much in advance. :)

**Comment by daerduoCarey** [comment]
It seems to be dependency version issue. More system settings are required to debug this type of question.

**Comment by Icxa** [comment]
Thank you very much for your concern. The issue has been resolved. I forgot to close the issue. I will do so now.
