### ISSUE TITLE
size mismatch in PartDecoder, m1: [64 x 50], m2: [100 x 100] 

### ISSUE THREAD

**Issue by Hydrogenion** [daerduoCarey/structurenet#2]
We meet problem that PartEncoder give a feature [64 x 50], but the input of PartDecoder is [100 x100]. It cause the RuntimeError: size mismatch, m1: [64 x 50], m2: [100 x 100] at /tmp/pip-req-build-9xcrj8au/aten/src/THC/generic/THCTensorMathBlas.cu:268

Please help me, thanks!

**Comment by daerduoCarey** [comment]
feat_len should be a parameter you can set in config.py. I think we are using 100 for all exps? Can you provide more details how do you get the 50-dim feature?

**Comment by Hydrogenion** [comment]
Why the program always be killed?
Some op always in cuda:0

**Comment by Hydrogenion** [comment]
I find the reason.
The cd loss will always run in cuda:0, if you just change device in config.py, it may cause some problem.
use os.environ["CUDA_VISIBLE_DEVICES"] = "2" will solve the problem.

BTW, my computer will kill the process which in cuda:0, so i find this problem.
