### ISSUE TITLE
Release more code

### ISSUE THREAD

**Issue by daerduoCarey** [daerduoCarey/structurenet#4]
-  [ToDo] Convert PartNet to StructureNet box-shapes
-  [ToDo] Blender visualization code
-  [ToDo] Code for applications (image --> structure, pc --> structure)

Please request here if you need more! Thank you!

Best,
Kaichun

**Comment by daerduoCarey** [comment]
code for GRASS baseline?

**Comment by hansongfang** [comment]
Thanks for sharing. When running detect_all_edges.py, it seems "../utils" is missing from this repository.

**Comment by daerduoCarey** [comment]
[Done] Blender visualization code

**Comment by dengyuhk** [comment]
Hi, the application part of your paper is interesting to me.  Could you release the application part (image --> structure)? 
Thanks in advance.

**Comment by tommaoer** [comment]
@hansongfang Hi, I am also using the code. You could comment the code about the '#visu'. the rest of the code is enough to do the edge detection.

**Comment by Mdemerdash** [comment]
@daerduoCarey  I really love this work and i'm doing my best to use it in my custom case. Did you realease code for number 1 ToDo Convert PartNet to StructureNet box-shapes?
