### ISSUE TITLE
ShapeNet ID for the PartNet data here

### ISSUE THREAD

**Issue by hansongfang** [daerduoCarey/structurenet#5]
Thanks for sharing this great project. I'm seeking if I could get the original shapeNet id for the provided data here. The shapeNet id is like "f859a1ed07d088be920de219c00d1c3b" and for the id used in StructureNet, it looks like "4144".

**Comment by daerduoCarey** [comment]
Please check https://github.com/daerduoCarey/partnet_dataset/blob/master/stats/all_valid_anno_info.txt
